apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/BartVB/argo-test.git'
        revision: HEAD
        directories:
          - path: 'addons/*'
          - path: 'addons/dont-install-this-application'  # Example for skipping an app
            exclude: true
          - path: 'addons/cert-manager'  # Example for skipping an app
            exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/BartVB/argo-test.git'
        path: 'addons/{{path.basename}}'
        helm:
          valueFiles:
            - 'values-development.yaml'  # Adapt this for each environment
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace = true
        automated:
          prune: true
          selfHeal: true