apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/BartVB/argo-test.git'
        revision: HEAD
        files:
          - path: 'addons/*/chart-config.yaml'
          - path: 'addons/*/chart-config-development.yaml'
  template:
    metadata:
      name: '{{component}}'
    spec:
      project: default
      sources:
        # Sample Helm Chart
        - repoURL: "{{chartURL}}"
          chart: "{{chart}}"
          targetRevision: "{{chartVersion}}"
          path: "{{chartPath}}"
          helm:
            # Helm releaseName resets the name of the installation
            # in the target cluster back to the expected name vs.
            # the ArgoCD Application CRD name which prepends the cluster name
            releaseName: "{{component}}"
            values: |-
              {{values}}
            ignoreMissingValueFiles: true
            valueFiles:
              - "$valuesRepo/addons/{{component}}/values.yaml"
              - "$valuesRepo/addons/{{component}}/values-development.yaml"
        # Values overrides
        - repoURL: "{{valuesURL}}"
          targetRevision: "{{valuesRevision}}"
          ref: valuesRepo
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{component}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true