env:
  proxy_listen: 0.0.0.0:8000, 0.0.0.0:8443 ssl http2
  real_ip_header: proxy_protocol
  trusted_ips: 0.0.0.0/0,::/0

proxy:
  externalTrafficPolicy: Local

  annotations: 
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "20"
    service.beta.kubernetes.io/linode-loadbalancer-default-protocol: "tcp"
    service.beta.kubernetes.io/linode-loadbalancer-proxy-protocol: "v1"
    service.beta.kubernetes.io/linode-loadbalancer-check-type: "connection"
    service.beta.kubernetes.io/linode-loadbalancer-hostname-only-ingress: "true"
  http:
    nodePort: 31111


ingressController:
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 350m
      memory: 750Mi

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "50%"
    maxUnavailable: "0%"

resources:
  limits:
    cpu: 1000m
    memory: 1G
  requests:
    cpu: 250m
    memory: 500M

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  ## targetCPUUtilizationPercentage only used if the cluster doesn't support autoscaling/v2beta
  # targetCPUUtilizationPercentage:
  ## Otherwise for clusters that do support autoscaling/v2beta, use metrics
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

serviceMonitor:
  # Specifies whether ServiceMonitor for Prometheus operator should be created
  # If you wish to gather metrics from a Kong instance with the proxy disabled (such as a hybrid control plane), see:
  # https://github.com/Kong/charts/blob/main/charts/kong/README.md#prometheus-operator-integration
  enabled: true
  interval: 5s
  # Specifies namespace, where ServiceMonitor should be installed
  namespace: kong
  labels:
    release: lke-monitor

manager:
  # Enable creating a Kubernetes service for Kong Manager
  enabled: false

portal:
  # Enable creating a Kubernetes service for the Developer Portal
  enabled: false

portalapi:
  # Enable creating a Kubernetes service for the Developer Portal API
  enabled: false
