---
kong:
  env:
    proxy_listen: 0.0.0.0:8000, 0.0.0.0:8443 ssl http2
    real_ip_header: proxy_protocol
    # Not used; the firewall limits incoming traffic on nodePorts to traffic from the loadbalancer.
    # trusted_ips: 167.235.218.206,2a01:4f8:c011:fc3::1

  proxy:
    externalTrafficPolicy: Local
    annotations:
      load-balancer.hetzner.cloud/name: kong-lb
      load-balancer.hetzner.cloud/location: fsn1
      load-balancer.hetzner.cloud/algorithm-type: least_connections
      load-balancer.hetzner.cloud/uses-proxyprotocol: true
      load-balancer.hetzner.cloud/node-selector: 
        node-role.kubernetes.io/control-plane: "false"
      # Not used, External DNS is not installed
      external-dns.alpha.kubernetes.io/hostname: kong.bokt-eu1

  dblessConfig:
    admissionWebhook:
      enabled: false
    resources:
      limits:
        cpu: 1000m
        memory: 1000Mi
      requests:
        cpu: 350m
        memory: 750Mi

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "0%"

  resources:
    limits:
      cpu: 1000m
      memory: 1G
    requests:
      cpu: 250m
      memory: 500M

  tolerations:
    - key: kubernetes.azure.com/scalesetpriority
      operator: "Equal"
      value: spot
      effect: NoSchedule

  replicaCount: 3

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 7
    behavior: {}
    ## targetCPUUtilizationPercentage only used if the cluster doesn't support autoscaling/v2 or autoscaling/v2beta
    targetCPUUtilizationPercentage:
    ## Otherwise for clusters that do support autoscaling/v2 or autoscaling/v2beta, use metrics
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 70

  podDisruptionBudget:
    enabled: true
    # Uncomment only one of the following when enabled is set to true
    # maxUnavailable: "50%"
    minAvailable: "33%"

  podSecurityPolicy:
    enabled: false

  serviceMonitor:
    # Specifies whether ServiceMonitor for Prometheus operator should be created
    # If you wish to gather metrics from a Kong instance with the proxy disabled (such as a hybrid control plane), see:
    # https://github.com/Kong/charts/blob/main/charts/kong/README.md#prometheus-operator-integration
    enabled: true
    interval: 10s
    namespace: kong
    labels:
      release: lke-monitor

  extraObjects:
    - apiVersion: configuration.konghq.com/v1
      kind: KongClusterPlugin
      metadata:
        name: prometheus
        annotations:
          kubernetes.io/ingress.class: kong
        labels:
          global: "true"
      config:
        per_consumer: false
        bandwidth_metrics: true
        latency_metrics: true
        status_code_metrics: true
      plugin: prometheus
