apiVersion: networking.k8s.io/v1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ui
  namespace: guestbook
spec:
  ingressClassName: kong
  rules:
    - host: guestbook.kong.bokt.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guestbook-ui
                port:
                  number: 80