cert-manager:
  enabled: true
  installCRDs: true

  # resources:
  #   requests:
  #     cpu: 75m
  #     memory: 200Mi
  #   limits:
  #     cpu: 75m
  #     memory: 200Mi

  podDisruptionBudget:
    enabled: true

  prometheus:
    servicemonitor:
      enabled: true
      labels:
        prometheus.io/scrap-with: kube-prometheus-stack
  extraArgs:
    - --logging-format=json
  webhook:
    extraArgs:
      - --logging-format=json
  cainjector:
    extraArgs:
      - --logging-format=json